### ISSUE TITLE
abnormal info in run

### ISSUE THREAD

**Issue by thuchengyun21** [The-carefree-solitary-wayfarer/THUAI6_player#6]
Up till now, I still haven't successfully opened a thuaipb playback file(potentially because an erroneous playback file was downloaded, as it appears to be 0kb); meantime, I do not remember all what was supposed to be in the original runGUIClient, so no UI can be provided.

With our current version, at somewhat 165 seconds into the game, one cmd window reports the following info:
![a](https://user-images.githubusercontent.com/89759247/235320234-06b5cbf9-14f8-4429-a933-3c0c00836085.jpg)
I wonder whether this is normal(e.g. addicted, quitted or sth) or might it be a bug. No other window reports the same info in the same timeframe.

**Comment by thuchengyun21** [comment]
@shangfengh

**Comment by Shawqeem** [comment]
A playback file is made only when a game is finished properly, not interrupted by the close option.
To review the playback file, you can write the commond line like this "@echo off

start cmd /k ..\Client\bin\Debug\net6.0-windows\Client.exe --playbackFile .\longtest.thuaipb --playbackSpeed 4" in your runGUIClient.cmd file. Remember, the path of Client.exe and the name of the playback file should be replaced by your own. Moreover, the speed to review should be set as an integer that belongs to [1,10].

As for the final issue, I don't know why either. Hope that we can debug together in the near future(:

では、お元気で。ご休み日を楽しんでよ～

**Comment by thuchengyun21** [comment]
Now out of date.
